### PR TITLE
Suggest fixes to `EntityRuleManager`

### PR DESCRIPTION
**Pull request by SuperNeon4ik**
Hey!

I tried the new `EntityRuleManager` and it didn't really work for me. 

The issues with it are:
- In the rule updates task in the `register()` func `holder.markAllUpdated()` was ran too early, making the loop never send updates.
- `onEntityShown` event would send packets just one moment too early and the client would throw `Received ClientboundSetExtraEntityDataPacket about unknown entity [id]` (probably an issue only on localhost actually, i don't have a server rn to test it on)

My suggested fixes are:
- Move the `holder.markAllUpdated()` to the end of the loop, so when filtering by `changePending` it can actually send data
- Add a 1 tick delay to `onEntityShown` event so the client has time to register the entity
- Remove `onNoxesiumPlayerRegistered` event, since when the player joins for each needed entity it's going to trigger the `onEntityShown` event

Open to suggestions!

### CODE REVIEW

**Comment by Aeltumn** [comment]
Listening to the noxesium register event is critical and does need to happen. I modelled this after MCC's implementation which is built into a fake entity system, and adding the hook on Noxesium registration fixed some critical bugs. It's for any entity that the player is already tracking when it gets registered with Noxesium as all past entities got ignored in the track event.

**Comment by SuperNeon4ik** [comment]
I see now. Thanks for clarifying.
Just read about the track event. Apparently it's Cancellable, and if cancelled the entity won't be shown to the player, so it's probably called before the entity packet is actually sent. So the issue is not about that the client does not have time to register the entity, but the packet about the entity is sent only after the setextradata packet. So, I would guess my assumption that this issue only happened on localhost is probably false and a 1-tick delay should be a decent solution. 
About hooking into the actual sending of the packet it would be possible with smth like ProtocolLib, but I don't think this is an appropriate place to use it. Maybe you have any ideas on that?

This is currently the only issue I'm facing with the server implementation on `2.3.3-SNAPSHOT`.

**Comment by Aeltumn** [comment]
After looking at the paper source code, the track event is indeed called early so it can be cancelled. Any packet handler would indeed make it better but I don't want either ProtocolLib or PacketEvents to be used for the base Noxesium implementation as they cause significant performance issues, especially ProtocolLib.

Waiting a tick is the best solution. But do make the listener priority = EventPriority.MONITOR and ignoreCancelled = true. I'll merge it after that!

**Comment by SuperNeon4ik** [comment]
Sounds great! Thank you!

**Pull request merged**
