### PR TITLE
Raise HUD held item name to avoid overlapping faction icons in lobbies

### PR DESCRIPTION
**Pull request by lucyydotp**
Before:

After:

It's worth pointing out that this does slightly raise the height of the text all the time. Whether this is an issue is debatable, it's only a very minor difference.

Vanilla for comparison:
image

### CODE REVIEW

**Comment by lucyydotp** [comment]
Ooh I've just remembered that other servers exist and probably don't want this - maybe we'd want to gate this to only happen on island?

**Comment by Aeltumn** [comment]
You can tie this into the ServerRule system that exists to allow servers to customise how many pixels it gets adjusted by.

**Comment by lucyydotp** [comment]
How's that?

**Comment by Aeltumn** [comment]
I'll get back to you after I've had time to implement ServerRule's on Island's server side and made it sent an adjust by value. The code looks good here, just needs the server to cooperate now.

**Pull request merged**
